package jaio.selection.bean;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

import java.util.ArrayList;
import java.util.List;

/**
 * Candidato generated by hbm2java
 */
public class ContInfoCandidatoListBean implements java.io.Serializable {

    String id;
    List<InfoCandidatoListBean> listaInfoCandidato = new ArrayList<>();

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public List<InfoCandidatoListBean> getListaInfoCandidato() {
        return listaInfoCandidato;
    }

    public void setListaInfoCandidato(List<InfoCandidatoListBean> listaInfoCandidato) {
        this.listaInfoCandidato = listaInfoCandidato;
    }

}
