package jaio.selection.bean;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

import java.util.ArrayList;
import java.util.List;

/**
 * Candidato generated by hbm2java
 */
public class InfoCandidatoListBean implements java.io.Serializable {

    private List<CandidatoBean> listaCandidato = new ArrayList<>();
    private List<AcademicaBean> listaAcademica = new ArrayList<>();
    private List<ConocimientoBean> listaConocimiento = new ArrayList<>();
    private List<ExperienciaBean> listaExperiencia = new ArrayList<>();
    private List<ReferenciaBean> listaReferencia = new ArrayList<>();

    public List<CandidatoBean> getListaCandidato() {
        return listaCandidato;
    }

    public void setListaCandidato(List<CandidatoBean> listaCandidato) {
        this.listaCandidato = listaCandidato;
    }

    public List<AcademicaBean> getListaAcademica() {
        return listaAcademica;
    }

    public void setListaAcademica(List<AcademicaBean> listaAcademica) {
        this.listaAcademica = listaAcademica;
    }

    public List<ConocimientoBean> getListaConocimiento() {
        return listaConocimiento;
    }

    public void setListaConocimiento(List<ConocimientoBean> listaConocimiento) {
        this.listaConocimiento = listaConocimiento;
    }

    public List<ExperienciaBean> getListaExperiencia() {
        return listaExperiencia;
    }

    public void setListaExperiencia(List<ExperienciaBean> listaExperiencia) {
        this.listaExperiencia = listaExperiencia;
    }

    public List<ReferenciaBean> getListaReferencia() {
        return listaReferencia;
    }

    public void setListaReferencia(List<ReferenciaBean> listaReferencia) {
        this.listaReferencia = listaReferencia;
    }

}
