package jaio.selection.bean;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

import jaio.selection.orm.*;

/**
 * ModeloPregunta generated by hbm2java
 */
public class ModeloAjustesCalcBean implements java.io.Serializable {

    private String id;
    private ModeloEvaluacion modeloEvaluacion;
    private String concepto;
    private String tipo;
    private String dato;

    public ModeloAjustesCalcBean() {
    }

    public ModeloAjustesCalcBean(ModeloEvaluacion modeloEvaluacion, String concepto, String tipo, String dato) {
        this.modeloEvaluacion = modeloEvaluacion;
        this.concepto = concepto;
        this.tipo = tipo;
        this.dato = dato;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ModeloEvaluacion getModeloEvaluacion() {
        return modeloEvaluacion;
    }

    public void setModeloEvaluacion(ModeloEvaluacion modeloEvaluacion) {
        this.modeloEvaluacion = modeloEvaluacion;
    }

    public String getConcepto() {
        return concepto;
    }

    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getDato() {
        return dato;
    }

    public void setDato(String dato) {
        this.dato = dato;
    }

}
