package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BateriaPersonalizada generated by hbm2java
 */
public class BateriaPersonalizada implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private Date fechaCreacion;
    private String nombrePerfil;
    private int estado;
    private String resena;
    private int horasEstimadasTotal;
    private int minutosEstimadosTotal;
    private Set bateriaEvaluacion = new HashSet(0);
    private Set evaluacionPerfil = new HashSet(0);

    public BateriaPersonalizada() {
    }

    public BateriaPersonalizada(String nombre, Date fechaCreacion, int estado, int horasEstimadasTotal, int minutosEstimadosTotal) {
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
        this.horasEstimadasTotal = horasEstimadasTotal;
        this.minutosEstimadosTotal = minutosEstimadosTotal;
    }

    public BateriaPersonalizada(String nombre, Date fechaCreacion, int estado, String resena, int horasEstimadasTotal, int minutosEstimadosTotal, Set bateriaEvaluacion, Set evaluacionPerfil) {
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
        this.resena = resena;
        this.horasEstimadasTotal = horasEstimadasTotal;
        this.minutosEstimadosTotal = minutosEstimadosTotal;
        this.bateriaEvaluacion = bateriaEvaluacion;
        this.evaluacionPerfil = evaluacionPerfil;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    public String getNombrePerfil() {
        return this.nombrePerfil;
    }

    public void setNombrePerfil(String nombrePerfil) {
        this.nombrePerfil = nombrePerfil;
    }

    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public String getResena() {
        return this.resena;
    }

    public void setResena(String resena) {
        this.resena = resena;
    }

    public int getHorasEstimadasTotal() {
        return this.horasEstimadasTotal;
    }

    public void setHorasEstimadasTotal(int horasEstimadasTotal) {
        this.horasEstimadasTotal = horasEstimadasTotal;
    }

    public int getMinutosEstimadosTotal() {
        return this.minutosEstimadosTotal;
    }

    public void setMinutosEstimadosTotal(int minutosEstimadosTotal) {
        this.minutosEstimadosTotal = minutosEstimadosTotal;
    }

    public Set getBateriaEvaluacion() {
        return this.bateriaEvaluacion;
    }

    public void setBateriaEvaluacion(Set bateriaEvaluacion) {
        this.bateriaEvaluacion = bateriaEvaluacion;
    }

    public Set getEvaluacionPerfil() {
        return this.evaluacionPerfil;
    }

    public void setEvaluacionPerfil(Set evaluacionPerfil) {
        this.evaluacionPerfil = evaluacionPerfil;
    }
 
}
