package jaio.selection.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA



/**
 * Elemento generated by hbm2java
 */
public class Elemento  implements java.io.Serializable {


     private Integer elIdElementoPk;
     private int elInActivo;
     private int elNuOrden;
     private String elTxDescripcion;
     private Integer elInUsaEscala;
     private String elTxValor1;
     private byte[] elCadena;

    public Elemento() {
    }

	
    public Integer getElIdElementoPk() {
        return this.elIdElementoPk;
    }
    
    public void setElIdElementoPk(Integer elIdElementoPk) {
        this.elIdElementoPk = elIdElementoPk;
    }
    public int getElInActivo() {
        return this.elInActivo;
    }
    
    public void setElInActivo(int elInActivo) {
        this.elInActivo = elInActivo;
    }
    public int getElNuOrden() {
        return this.elNuOrden;
    }
    
    public void setElNuOrden(int elNuOrden) {
        this.elNuOrden = elNuOrden;
    }
    public String getElTxDescripcion() {
        return this.elTxDescripcion;
    }
    
    public void setElTxDescripcion(String elTxDescripcion) {
        this.elTxDescripcion = elTxDescripcion;
    }
    public Integer getElInUsaEscala() {
        return this.elInUsaEscala;
    }
    
    public void setElInUsaEscala(Integer elInUsaEscala) {
        this.elInUsaEscala = elInUsaEscala;
    }
    public String getElTxValor1() {
        return this.elTxValor1;
    }
    
    public void setElTxValor1(String elTxValor1) {
        this.elTxValor1 = elTxValor1;
    }
    public byte[] getElCadena() {
        return this.elCadena;
    }
    
    public void setElCadena(byte[] elCadena) {
        this.elCadena = elCadena;
    }




}


