package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

/**
 * Elemento generated by hbm2java
 */
public class Elemento implements java.io.Serializable {

    private Integer id;
    private Definicion definicion;
    private String descripcion;
    private int orden;
    private byte activo;

    public Elemento() {
    }

    public Elemento(Definicion definicion, String descripcion, int orden, byte activo) {
        this.definicion = definicion;
        this.descripcion = descripcion;
        this.orden = orden;
        this.activo = activo;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Definicion getDefinicion() {
        return this.definicion;
    }

    public void setDefinicion(Definicion definicion) {
        this.definicion = definicion;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public int getOrden() {
        return this.orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    public byte getActivo() {
        return this.activo;
    }

    public void setActivo(byte activo) {
        this.activo = activo;
    }

}
