package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String nombre;
     private Date fechaRegistro;
     private int estado;
     private byte predeterminado;
     private byte[] imagen;
     private String tipo_imagen;
     private Set areas = new HashSet(0);
     private Set areas_1 = new HashSet(0);
     private Set perfils = new HashSet(0);
     private Set perfils_1 = new HashSet(0);

    public Empresa() {
    }


    public Empresa(Usuario usuario, String nombre, Date fechaRegistro, int estado, byte predeterminado) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.fechaRegistro = fechaRegistro;
        this.estado = estado;
        this.predeterminado = predeterminado;
    }
    public Empresa(Usuario usuario, String nombre, Date fechaRegistro, int estado, byte predeterminado, byte[] imagen, String tipo_imagen, Set areas, Set areas_1, Set perfils, Set perfils_1) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.predeterminado = predeterminado;
       this.imagen = imagen;
       this.tipo_imagen = tipo_imagen;
       this.areas = areas;
       this.areas_1 = areas_1;
       this.perfils = perfils;
       this.perfils_1 = perfils_1;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }


    public String getTipo_imagen() {
		return tipo_imagen;
	}


	public void setTipo_imagen(String tipo_imagen) {
		this.tipo_imagen = tipo_imagen;
	}


	public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }
    public byte getPredeterminado() {
        return this.predeterminado;
    }

    public void setPredeterminado(byte predeterminado) {
        this.predeterminado = predeterminado;
    }
    public byte[] getImagen() {
        return this.imagen;
    }

    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public Set getAreas() {
        return this.areas;
    }

    public void setAreas(Set areas) {
        this.areas = areas;
    }
    public Set getAreas_1() {
        return this.areas_1;
    }

    public void setAreas_1(Set areas_1) {
        this.areas_1 = areas_1;
    }
    public Set getPerfils() {
        return this.perfils;
    }

    public void setPerfils(Set perfils) {
        this.perfils = perfils;
    }
    public Set getPerfils_1() {
        return this.perfils_1;
    }

    public void setPerfils_1(Set perfils_1) {
        this.perfils_1 = perfils_1;
    }




}


