package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

/**
 * EvaluacionPerfil generated by hbm2java
 */
public class EvaluacionPerfil implements java.io.Serializable {

    private EvaluacionPerfilId id;
    private BateriaPersonalizada bateriaPersonalizada;
    private int estado;
    private ProcesoSeleccion procesoSeleccion;
    

    public EvaluacionPerfil() {
    }

    public EvaluacionPerfil(EvaluacionPerfilId id, BateriaPersonalizada bateriaPersonalizada, int estado,ProcesoSeleccion procesoSeleccion) {
        this.id = id;
        this.bateriaPersonalizada = bateriaPersonalizada;
        this.estado = estado;
        this.procesoSeleccion = procesoSeleccion;
    }

    public EvaluacionPerfilId getId() {
        return this.id;
    }

    public void setId(EvaluacionPerfilId id) {
        this.id = id;
    }

    public BateriaPersonalizada getBateriaPersonalizada() {
        return this.bateriaPersonalizada;
    }

    public void setBateriaPersonalizada(BateriaPersonalizada bateriaPersonalizada) {
        this.bateriaPersonalizada = bateriaPersonalizada;
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }
    
    public ProcesoSeleccion getProcesoSeleccion() {
        return procesoSeleccion;
    }

    public void setProcesoSeleccion(ProcesoSeleccion procesoSeleccion) {
        this.procesoSeleccion = procesoSeleccion;
    }
    
}
