package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

/**
 * EvaluacionPerfilId generated by hbm2java
 */
public class EvaluacionPerfilId implements java.io.Serializable {

    private int procesoSeleccionId;
    private int bateriaPersonalizadaId;
    private int estado;

    public EvaluacionPerfilId() {
    }

    public EvaluacionPerfilId(int procesoSeleccionId, int bateriaPersonalizadaId, int estado) {
        this.procesoSeleccionId = procesoSeleccionId;
        this.bateriaPersonalizadaId = bateriaPersonalizadaId;
        this.estado = estado;
    }

    public int getProcesoSeleccionId() {
        return this.procesoSeleccionId;
    }

    public void setProcesoSeleccionId(int procesoSeleccionId) {
        this.procesoSeleccionId = procesoSeleccionId;
    }

    public int getBateriaPersonalizadaId() {
        return this.bateriaPersonalizadaId;
    }

    public void setBateriaPersonalizadaId(int bateriaPersonalizadaId) {
        this.bateriaPersonalizadaId = bateriaPersonalizadaId;
    }

    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof EvaluacionPerfilId)) {
            return false;
        }
        EvaluacionPerfilId castOther = (EvaluacionPerfilId) other;

        return (this.getProcesoSeleccionId() == castOther.getProcesoSeleccionId())
                && (this.getBateriaPersonalizadaId() == castOther.getBateriaPersonalizadaId())
                && (this.getEstado() == castOther.getEstado());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getProcesoSeleccionId();
        result = 37 * result + this.getBateriaPersonalizadaId();
        result = 37 * result + this.getEstado();
        return result;
    }

}
