package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

/**
 * EvaluacionPerfil generated by hbm2java
 */
public class EvaluacionPerfil implements java.io.Serializable {

    private EvaluacionPerfilId id;
    private BateriaPersonalizada bateriaPersonalizada;
    private Perfil perfil;

    public EvaluacionPerfil() {
    }

    public EvaluacionPerfil(EvaluacionPerfilId id, BateriaPersonalizada bateriaPersonalizada, Perfil perfil) {
        this.id = id;
        this.bateriaPersonalizada = bateriaPersonalizada;
        this.perfil = perfil;
    }

    public EvaluacionPerfilId getId() {
        return this.id;
    }

    public void setId(EvaluacionPerfilId id) {
        this.id = id;
    }

    public BateriaPersonalizada getBateriaPersonalizada() {
        return this.bateriaPersonalizada;
    }

    public void setBateriaPersonalizada(BateriaPersonalizada bateriaPersonalizada) {
        this.bateriaPersonalizada = bateriaPersonalizada;
    }

    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

}
