package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final



/**
 * ModeloEvaluacionXCompetencia generated by hbm2java
 */
public class ModeloEvaluacionXCompetencia  implements java.io.Serializable {


     private ModeloEvaluacionXCompetenciaId id;
     private ModeloCompetencia modeloCompetencia;
     private ModeloEvaluacion modeloEvaluacion;

    public ModeloEvaluacionXCompetencia() {
    }

    public ModeloEvaluacionXCompetencia(ModeloEvaluacionXCompetenciaId id, ModeloCompetencia modeloCompetencia, ModeloEvaluacion modeloEvaluacion) {
       this.id = id;
       this.modeloCompetencia = modeloCompetencia;
       this.modeloEvaluacion = modeloEvaluacion;
    }
   
    public ModeloEvaluacionXCompetenciaId getId() {
        return this.id;
    }
    
    public void setId(ModeloEvaluacionXCompetenciaId id) {
        this.id = id;
    }
    public ModeloCompetencia getModeloCompetencia() {
        return this.modeloCompetencia;
    }
    
    public void setModeloCompetencia(ModeloCompetencia modeloCompetencia) {
        this.modeloCompetencia = modeloCompetencia;
    }
    public ModeloEvaluacion getModeloEvaluacion() {
        return this.modeloEvaluacion;
    }
    
    public void setModeloEvaluacion(ModeloEvaluacion modeloEvaluacion) {
        this.modeloEvaluacion = modeloEvaluacion;
    }




}


