package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final


import java.util.HashSet;
import java.util.Set;

/**
 * ModeloLibro generated by hbm2java
 */
public class ModeloLibro  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String autor;
     private String adaptacion;
     private String resena;
     private Integer minutosEstimados;
     private Set modeloEvaluacions = new HashSet(0);
     private Set modeloEvaluacions_1 = new HashSet(0);

    public ModeloLibro() {
    }

	
    public ModeloLibro(String nombre) {
        this.nombre = nombre;
    }
    public ModeloLibro(String nombre, String autor, String adaptacion, String resena, Integer minutosEstimados, Set modeloEvaluacions, Set modeloEvaluacions_1) {
       this.nombre = nombre;
       this.autor = autor;
       this.adaptacion = adaptacion;
       this.resena = resena;
       this.minutosEstimados = minutosEstimados;
       this.modeloEvaluacions = modeloEvaluacions;
       this.modeloEvaluacions_1 = modeloEvaluacions_1;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getAdaptacion() {
        return this.adaptacion;
    }
    
    public void setAdaptacion(String adaptacion) {
        this.adaptacion = adaptacion;
    }
    public String getResena() {
        return this.resena;
    }
    
    public void setResena(String resena) {
        this.resena = resena;
    }
    
    
    public Integer getMinutosEstimados() {
        return this.minutosEstimados;
    }
    
    public void setMinutosEstimados(Integer minutosEstimados) {
        this.minutosEstimados = minutosEstimados;
    }
    public Set getModeloEvaluacions() {
        return this.modeloEvaluacions;
    }
    
    public void setModeloEvaluacions(Set modeloEvaluacions) {
        this.modeloEvaluacions = modeloEvaluacions;
    }
    public Set getModeloEvaluacions_1() {
        return this.modeloEvaluacions_1;
    }
    
    public void setModeloEvaluacions_1(Set modeloEvaluacions_1) {
        this.modeloEvaluacions_1 = modeloEvaluacions_1;
    }




}


