package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ModeloPregunta generated by hbm2java
 */
public class ModeloAjustesCalc implements java.io.Serializable {

    private Integer id;
    private ModeloEvaluacion modeloEvaluacion;
    private String concepto;
    private int tipo;
    private BigDecimal dato;

    public ModeloAjustesCalc() {
    }

    public ModeloAjustesCalc(ModeloEvaluacion modeloEvaluacion, String concepto, int tipo, BigDecimal dato) {
        this.modeloEvaluacion = modeloEvaluacion;
        this.concepto = concepto;
        this.tipo = tipo;
        this.dato = dato;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ModeloEvaluacion getModeloEvaluacion() {
        return modeloEvaluacion;
    }

    public void setModeloEvaluacion(ModeloEvaluacion modeloEvaluacion) {
        this.modeloEvaluacion = modeloEvaluacion;
    }

    public String getConcepto() {
        return concepto;
    }

    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    public int getTipo() {
        return tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    public BigDecimal getDato() {
        return dato;
    }

    public void setDato(BigDecimal dato) {
        this.dato = dato;
    }

}
