package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

/**
 * ModeloCompetenciaSinonimo generated by hbm2java
 */
public class ModeloCompetenciaSinonimo implements java.io.Serializable {

    private Integer id;
    private ModeloCompetencia modeloCompetencia;
    private String palabra;

    public ModeloCompetenciaSinonimo() {
    }

    public ModeloCompetenciaSinonimo(ModeloCompetencia modeloCompetencia, String palabra) {
        this.modeloCompetencia = modeloCompetencia;
        this.palabra = palabra;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ModeloCompetencia getModeloCompetencia() {
        return this.modeloCompetencia;
    }

    public void setModeloCompetencia(ModeloCompetencia modeloCompetencia) {
        this.modeloCompetencia = modeloCompetencia;
    }

    public String getPalabra() {
        return this.palabra;
    }

    public void setPalabra(String palabra) {
        this.palabra = palabra;
    }

}
