package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcesoSeleccion generated by hbm2java
 */
public class ProcesoSeleccion implements java.io.Serializable {

    private Integer id;
    private Perfil perfil;
    private Date fechaRegistro;
    private String descripcion;
    private int estado;
    private Set candidatos = new HashSet(0);
    private Set notificacioneses = new HashSet(0);
    private Set comunicadoProcesos = new HashSet(0);

    public ProcesoSeleccion() {
    }

    public ProcesoSeleccion(Perfil perfil, Date fechaRegistro, String descripcion, int estado) {
        this.perfil = perfil;
        this.fechaRegistro = fechaRegistro;
        this.descripcion = descripcion;
        this.estado = estado;
    }

    public ProcesoSeleccion(Perfil perfil, Date fechaRegistro, String descripcion, int estado, Set candidatos, Set notificacioneses, Set candidatos_1, Set comunicadoProcesos, Set comunicadoProcesos_1, Set notificacioneses_1) {
        this.perfil = perfil;
        this.fechaRegistro = fechaRegistro;
        this.descripcion = descripcion;
        this.estado = estado;
        this.candidatos = candidatos;
        this.notificacioneses = notificacioneses;
        this.comunicadoProcesos = comunicadoProcesos;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public Set getCandidatos() {
        return this.candidatos;
    }

    public void setCandidatos(Set candidatos) {
        this.candidatos = candidatos;
    }

    public Set getNotificacioneses() {
        return this.notificacioneses;
    }

    public void setNotificacioneses(Set notificacioneses) {
        this.notificacioneses = notificacioneses;
    }

    public Set getComunicadoProcesos() {
        return this.comunicadoProcesos;
    }

    public void setComunicadoProcesos(Set comunicadoProcesos) {
        this.comunicadoProcesos = comunicadoProcesos;
    }

}
