package jaio.selection.orm;
// Generated 06/11/2017 06:07:26 PM by Hibernate Tools 5.1.4.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String correo;
     private String nombreCompleto;
     private Date fechaRegistro;
     private int estado;
     private String contrasena;
     private int sexo;
     private Set empresas = new HashSet(0);
     private Set empresas_1 = new HashSet(0);

    public Usuario() {
    }


    public Usuario(String correo, String nombreCompleto, Date fechaRegistro, int estado, String contrasena) {
        this.correo = correo;
        this.nombreCompleto = nombreCompleto;
        this.fechaRegistro = fechaRegistro;
        this.estado = estado;
        this.contrasena = contrasena;
    }
    public Usuario(String correo, String nombreCompleto, Date fechaRegistro, int estado, String contrasena, int sexo, Set empresas, Set empresas_1) {
       this.correo = correo;
       this.nombreCompleto = nombreCompleto;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.sexo = sexo;
       this.contrasena = contrasena;
       this.empresas = empresas;
       this.empresas_1 = empresas_1;
    }

    public Integer getId() {
        return this.id;
    }



    public int getSexo() {
		return sexo;
	}


	public void setSexo(int sexo) {
		this.sexo = sexo;
	}


	public void setId(Integer id) {
        this.id = id;
    }
    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }

    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }
    public String getContrasena() {
        return this.contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getEmpresas() {
        return this.empresas;
    }

    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }
    public Set getEmpresas_1() {
        return this.empresas_1;
    }

    public void setEmpresas_1(Set empresas_1) {
        this.empresas_1 = empresas_1;
    }




}


