package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", catalog = "jaioselectiondb")
public class Area implements java.io.Serializable {

	private Integer id;
	private Area area;
	private Empresa empresa;
	private String descripcion;
	private Date fechaRegistro;
	private int estado;
	private Set<Area> areas = new HashSet<Area>(0);
	private Set<Perfil> perfils = new HashSet<Perfil>(0);

	public Area() {
	}

	public Area(Empresa empresa, String descripcion, Date fechaRegistro, int estado) {
		this.empresa = empresa;
		this.descripcion = descripcion;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
	}

	public Area(Area area, Empresa empresa, String descripcion, Date fechaRegistro, int estado, Set<Area> areas,
			Set<Perfil> perfils) {
		this.area = area;
		this.empresa = empresa;
		this.descripcion = descripcion;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
		this.areas = areas;
		this.perfils = perfils;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_herarquia_id")
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empresa_id", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro", nullable = false, length = 10)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Area> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

}
