package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BateriaPersonalizada generated by hbm2java
 */
@Entity
@Table(name = "bateria_personalizada", catalog = "jaioselectiondb")
public class BateriaPersonalizada implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Date fechaCreacion;
	private int estado;
	private String resena;
	private int horasEstimadasTotal;
	private int minutosEstimadosTotal;
	private Set<BateriaEvaluacion> bateriaEvaluacions = new HashSet<BateriaEvaluacion>(0);
	private Set<EvaluacionPerfil> evaluacionPerfils = new HashSet<EvaluacionPerfil>(0);

	public BateriaPersonalizada() {
	}

	public BateriaPersonalizada(String nombre, Date fechaCreacion, int estado, int horasEstimadasTotal,
			int minutosEstimadosTotal) {
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.horasEstimadasTotal = horasEstimadasTotal;
		this.minutosEstimadosTotal = minutosEstimadosTotal;
	}

	public BateriaPersonalizada(String nombre, Date fechaCreacion, int estado, String resena, int horasEstimadasTotal,
			int minutosEstimadosTotal, Set<BateriaEvaluacion> bateriaEvaluacions,
			Set<EvaluacionPerfil> evaluacionPerfils) {
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.resena = resena;
		this.horasEstimadasTotal = horasEstimadasTotal;
		this.minutosEstimadosTotal = minutosEstimadosTotal;
		this.bateriaEvaluacions = bateriaEvaluacions;
		this.evaluacionPerfils = evaluacionPerfils;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", nullable = false, length = 10)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Column(name = "resena", length = 2000)
	public String getResena() {
		return this.resena;
	}

	public void setResena(String resena) {
		this.resena = resena;
	}

	@Column(name = "horas_estimadas_total", nullable = false)
	public int getHorasEstimadasTotal() {
		return this.horasEstimadasTotal;
	}

	public void setHorasEstimadasTotal(int horasEstimadasTotal) {
		this.horasEstimadasTotal = horasEstimadasTotal;
	}

	@Column(name = "minutos_estimados_total", nullable = false)
	public int getMinutosEstimadosTotal() {
		return this.minutosEstimadosTotal;
	}

	public void setMinutosEstimadosTotal(int minutosEstimadosTotal) {
		this.minutosEstimadosTotal = minutosEstimadosTotal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bateriaPersonalizada")
	public Set<BateriaEvaluacion> getBateriaEvaluacions() {
		return this.bateriaEvaluacions;
	}

	public void setBateriaEvaluacions(Set<BateriaEvaluacion> bateriaEvaluacions) {
		this.bateriaEvaluacions = bateriaEvaluacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bateriaPersonalizada")
	public Set<EvaluacionPerfil> getEvaluacionPerfils() {
		return this.evaluacionPerfils;
	}

	public void setEvaluacionPerfils(Set<EvaluacionPerfil> evaluacionPerfils) {
		this.evaluacionPerfils = evaluacionPerfils;
	}

}
