package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BateriaEvaluacionId generated by hbm2java
 */
@Embeddable
public class BateriaEvaluacionId implements java.io.Serializable {

	private int modeloEvaluacionId;
	private int bateriaPersonalizadaId;

	public BateriaEvaluacionId() {
	}

	public BateriaEvaluacionId(int modeloEvaluacionId, int bateriaPersonalizadaId) {
		this.modeloEvaluacionId = modeloEvaluacionId;
		this.bateriaPersonalizadaId = bateriaPersonalizadaId;
	}

	@Column(name = "modelo_evaluacion_id", nullable = false)
	public int getModeloEvaluacionId() {
		return this.modeloEvaluacionId;
	}

	public void setModeloEvaluacionId(int modeloEvaluacionId) {
		this.modeloEvaluacionId = modeloEvaluacionId;
	}

	@Column(name = "bateria_personalizada_id", nullable = false)
	public int getBateriaPersonalizadaId() {
		return this.bateriaPersonalizadaId;
	}

	public void setBateriaPersonalizadaId(int bateriaPersonalizadaId) {
		this.bateriaPersonalizadaId = bateriaPersonalizadaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BateriaEvaluacionId))
			return false;
		BateriaEvaluacionId castOther = (BateriaEvaluacionId) other;

		return (this.getModeloEvaluacionId() == castOther.getModeloEvaluacionId())
				&& (this.getBateriaPersonalizadaId() == castOther.getBateriaPersonalizadaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModeloEvaluacionId();
		result = 37 * result + this.getBateriaPersonalizadaId();
		return result;
	}

}
