package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BateriaEvaluacion generated by hbm2java
 */
@Entity
@Table(name = "bateria_evaluacion", catalog = "jaioselectiondb")
public class BateriaEvaluacion implements java.io.Serializable {

	private BateriaEvaluacionId id;
	private BateriaPersonalizada bateriaPersonalizada;
	private ModeloEvaluacion modeloEvaluacion;

	public BateriaEvaluacion() {
	}

	public BateriaEvaluacion(BateriaEvaluacionId id, BateriaPersonalizada bateriaPersonalizada,
			ModeloEvaluacion modeloEvaluacion) {
		this.id = id;
		this.bateriaPersonalizada = bateriaPersonalizada;
		this.modeloEvaluacion = modeloEvaluacion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "modeloEvaluacionId", column = @Column(name = "modelo_evaluacion_id", nullable = false)),
			@AttributeOverride(name = "bateriaPersonalizadaId", column = @Column(name = "bateria_personalizada_id", nullable = false)) })
	public BateriaEvaluacionId getId() {
		return this.id;
	}

	public void setId(BateriaEvaluacionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bateria_personalizada_id", nullable = false, insertable = false, updatable = false)
	public BateriaPersonalizada getBateriaPersonalizada() {
		return this.bateriaPersonalizada;
	}

	public void setBateriaPersonalizada(BateriaPersonalizada bateriaPersonalizada) {
		this.bateriaPersonalizada = bateriaPersonalizada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo_evaluacion_id", nullable = false, insertable = false, updatable = false)
	public ModeloEvaluacion getModeloEvaluacion() {
		return this.modeloEvaluacion;
	}

	public void setModeloEvaluacion(ModeloEvaluacion modeloEvaluacion) {
		this.modeloEvaluacion = modeloEvaluacion;
	}

}
