package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComunicadoProcesoId generated by hbm2java
 */
@Embeddable
public class ComunicadoProcesoId implements java.io.Serializable {

	private int procesoSeleccionId;
	private int modeloComunicadoId;

	public ComunicadoProcesoId() {
	}

	public ComunicadoProcesoId(int procesoSeleccionId, int modeloComunicadoId) {
		this.procesoSeleccionId = procesoSeleccionId;
		this.modeloComunicadoId = modeloComunicadoId;
	}

	@Column(name = "proceso_seleccion_id", nullable = false)
	public int getProcesoSeleccionId() {
		return this.procesoSeleccionId;
	}

	public void setProcesoSeleccionId(int procesoSeleccionId) {
		this.procesoSeleccionId = procesoSeleccionId;
	}

	@Column(name = "modelo_comunicado_id", nullable = false)
	public int getModeloComunicadoId() {
		return this.modeloComunicadoId;
	}

	public void setModeloComunicadoId(int modeloComunicadoId) {
		this.modeloComunicadoId = modeloComunicadoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComunicadoProcesoId))
			return false;
		ComunicadoProcesoId castOther = (ComunicadoProcesoId) other;

		return (this.getProcesoSeleccionId() == castOther.getProcesoSeleccionId())
				&& (this.getModeloComunicadoId() == castOther.getModeloComunicadoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProcesoSeleccionId();
		result = 37 * result + this.getModeloComunicadoId();
		return result;
	}

}
