package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComunicadoProceso generated by hbm2java
 */
@Entity
@Table(name = "comunicado_proceso", catalog = "jaioselectiondb")
public class ComunicadoProceso implements java.io.Serializable {

	private ComunicadoProcesoId id;
	private ModeloComunicado modeloComunicado;
	private ProcesoSeleccion procesoSeleccion;

	public ComunicadoProceso() {
	}

	public ComunicadoProceso(ComunicadoProcesoId id, ModeloComunicado modeloComunicado,
			ProcesoSeleccion procesoSeleccion) {
		this.id = id;
		this.modeloComunicado = modeloComunicado;
		this.procesoSeleccion = procesoSeleccion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "procesoSeleccionId", column = @Column(name = "proceso_seleccion_id", nullable = false)),
			@AttributeOverride(name = "modeloComunicadoId", column = @Column(name = "modelo_comunicado_id", nullable = false)) })
	public ComunicadoProcesoId getId() {
		return this.id;
	}

	public void setId(ComunicadoProcesoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo_comunicado_id", nullable = false, insertable = false, updatable = false)
	public ModeloComunicado getModeloComunicado() {
		return this.modeloComunicado;
	}

	public void setModeloComunicado(ModeloComunicado modeloComunicado) {
		this.modeloComunicado = modeloComunicado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proceso_seleccion_id", nullable = false, insertable = false, updatable = false)
	public ProcesoSeleccion getProcesoSeleccion() {
		return this.procesoSeleccion;
	}

	public void setProcesoSeleccion(ProcesoSeleccion procesoSeleccion) {
		this.procesoSeleccion = procesoSeleccion;
	}

}
