package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Definicion generated by hbm2java
 */
@Entity
@Table(name = "definicion", catalog = "jaioselectiondb")
public class Definicion implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private Set<Elemento> elementos = new HashSet<Elemento>(0);

	public Definicion() {
	}

	public Definicion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Definicion(String descripcion, Set<Elemento> elementos) {
		this.descripcion = descripcion;
		this.elementos = elementos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "definicion")
	public Set<Elemento> getElementos() {
		return this.elementos;
	}

	public void setElementos(Set<Elemento> elementos) {
		this.elementos = elementos;
	}

}
