package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Elemento generated by hbm2java
 */
@Entity
@Table(name = "elemento", catalog = "jaioselectiondb")
public class Elemento implements java.io.Serializable {

	private Integer id;
	private Definicion definicion;
	private String descripcion;
	private int orden;
	private byte activo;

	public Elemento() {
	}

	public Elemento(Definicion definicion, String descripcion, int orden, byte activo) {
		this.definicion = definicion;
		this.descripcion = descripcion;
		this.orden = orden;
		this.activo = activo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "definicion_id", nullable = false)
	public Definicion getDefinicion() {
		return this.definicion;
	}

	public void setDefinicion(Definicion definicion) {
		this.definicion = definicion;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@Column(name = "activo", nullable = false)
	public byte getActivo() {
		return this.activo;
	}

	public void setActivo(byte activo) {
		this.activo = activo;
	}

}
