package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "jaioselectiondb")
public class Empresa implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private String nombre;
	private Date fechaRegistro;
	private int estado;
	private byte predeterminado;
	private byte[] imagen;
	private Set<Area> areas = new HashSet<Area>(0);
	private Set<Perfil> perfils = new HashSet<Perfil>(0);

	public Empresa() {
	}

	public Empresa(Usuario usuario, String nombre, Date fechaRegistro, int estado, byte predeterminado) {
		this.usuario = usuario;
		this.nombre = nombre;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
		this.predeterminado = predeterminado;
	}

	public Empresa(Usuario usuario, String nombre, Date fechaRegistro, int estado, byte predeterminado, byte[] imagen,
			Set<Area> areas, Set<Perfil> perfils) {
		this.usuario = usuario;
		this.nombre = nombre;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
		this.predeterminado = predeterminado;
		this.imagen = imagen;
		this.areas = areas;
		this.perfils = perfils;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro", nullable = false, length = 10)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Column(name = "predeterminado", nullable = false)
	public byte getPredeterminado() {
		return this.predeterminado;
	}

	public void setPredeterminado(byte predeterminado) {
		this.predeterminado = predeterminado;
	}

	@Column(name = "imagen")
	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Area> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

}
