package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EvaluacionPerfilId generated by hbm2java
 */
@Embeddable
public class EvaluacionPerfilId implements java.io.Serializable {

	private int perfilId;
	private int bateriaPersonalizadaId;
	private int estado;

	public EvaluacionPerfilId() {
	}

	public EvaluacionPerfilId(int perfilId, int bateriaPersonalizadaId, int estado) {
		this.perfilId = perfilId;
		this.bateriaPersonalizadaId = bateriaPersonalizadaId;
		this.estado = estado;
	}

	@Column(name = "perfil_id", nullable = false)
	public int getPerfilId() {
		return this.perfilId;
	}

	public void setPerfilId(int perfilId) {
		this.perfilId = perfilId;
	}

	@Column(name = "bateria_personalizada_id", nullable = false)
	public int getBateriaPersonalizadaId() {
		return this.bateriaPersonalizadaId;
	}

	public void setBateriaPersonalizadaId(int bateriaPersonalizadaId) {
		this.bateriaPersonalizadaId = bateriaPersonalizadaId;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EvaluacionPerfilId))
			return false;
		EvaluacionPerfilId castOther = (EvaluacionPerfilId) other;

		return (this.getPerfilId() == castOther.getPerfilId())
				&& (this.getBateriaPersonalizadaId() == castOther.getBateriaPersonalizadaId())
				&& (this.getEstado() == castOther.getEstado());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPerfilId();
		result = 37 * result + this.getBateriaPersonalizadaId();
		result = 37 * result + this.getEstado();
		return result;
	}

}
