package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EvaluacionPerfil generated by hbm2java
 */
@Entity
@Table(name = "evaluacion_perfil", catalog = "jaioselectiondb")
public class EvaluacionPerfil implements java.io.Serializable {

	private EvaluacionPerfilId id;
	private BateriaPersonalizada bateriaPersonalizada;
	private Perfil perfil;

	public EvaluacionPerfil() {
	}

	public EvaluacionPerfil(EvaluacionPerfilId id, BateriaPersonalizada bateriaPersonalizada, Perfil perfil) {
		this.id = id;
		this.bateriaPersonalizada = bateriaPersonalizada;
		this.perfil = perfil;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "perfilId", column = @Column(name = "perfil_id", nullable = false)),
			@AttributeOverride(name = "bateriaPersonalizadaId", column = @Column(name = "bateria_personalizada_id", nullable = false)),
			@AttributeOverride(name = "estado", column = @Column(name = "estado", nullable = false)) })
	public EvaluacionPerfilId getId() {
		return this.id;
	}

	public void setId(EvaluacionPerfilId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bateria_personalizada_id", nullable = false, insertable = false, updatable = false)
	public BateriaPersonalizada getBateriaPersonalizada() {
		return this.bateriaPersonalizada;
	}

	public void setBateriaPersonalizada(BateriaPersonalizada bateriaPersonalizada) {
		this.bateriaPersonalizada = bateriaPersonalizada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "perfil_id", nullable = false, insertable = false, updatable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

}
