package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InfoReferencia generated by hbm2java
 */
@Entity
@Table(name = "info_referencia", catalog = "jaioselectiondb")
public class InfoReferencia implements java.io.Serializable {

	private Integer id;
	private InfoExperiencia infoExperiencia;
	private String nombreCompleto;
	private String cargo;
	private String telefono;
	private String movil;

	public InfoReferencia() {
	}

	public InfoReferencia(InfoExperiencia infoExperiencia, String nombreCompleto, String cargo) {
		this.infoExperiencia = infoExperiencia;
		this.nombreCompleto = nombreCompleto;
		this.cargo = cargo;
	}

	public InfoReferencia(InfoExperiencia infoExperiencia, String nombreCompleto, String cargo, String telefono,
			String movil) {
		this.infoExperiencia = infoExperiencia;
		this.nombreCompleto = nombreCompleto;
		this.cargo = cargo;
		this.telefono = telefono;
		this.movil = movil;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "info_experiencia_id", nullable = false)
	public InfoExperiencia getInfoExperiencia() {
		return this.infoExperiencia;
	}

	public void setInfoExperiencia(InfoExperiencia infoExperiencia) {
		this.infoExperiencia = infoExperiencia;
	}

	@Column(name = "nombre_completo", nullable = false, length = 200)
	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	@Column(name = "cargo", nullable = false, length = 200)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "telefono", length = 50)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "movil", length = 50)
	public String getMovil() {
		return this.movil;
	}

	public void setMovil(String movil) {
		this.movil = movil;
	}

}
