package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InfoExperiencia generated by hbm2java
 */
@Entity
@Table(name = "info_experiencia", catalog = "jaioselectiondb")
public class InfoExperiencia implements java.io.Serializable {

	private Integer id;
	private Candidato candidato;
	private String empresa;
	private Date fechaInicio;
	private Date fechaFin;
	private byte[] logro;
	private String cargo;
	private Set<InfoReferencia> infoReferencias = new HashSet<InfoReferencia>(0);

	public InfoExperiencia() {
	}

	public InfoExperiencia(Candidato candidato, String empresa, Date fechaInicio, String cargo) {
		this.candidato = candidato;
		this.empresa = empresa;
		this.fechaInicio = fechaInicio;
		this.cargo = cargo;
	}

	public InfoExperiencia(Candidato candidato, String empresa, Date fechaInicio, Date fechaFin, byte[] logro,
			String cargo, Set<InfoReferencia> infoReferencias) {
		this.candidato = candidato;
		this.empresa = empresa;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.logro = logro;
		this.cargo = cargo;
		this.infoReferencias = infoReferencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidato_id", nullable = false)
	public Candidato getCandidato() {
		return this.candidato;
	}

	public void setCandidato(Candidato candidato) {
		this.candidato = candidato;
	}

	@Column(name = "empresa", nullable = false, length = 200)
	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "logro")
	public byte[] getLogro() {
		return this.logro;
	}

	public void setLogro(byte[] logro) {
		this.logro = logro;
	}

	@Column(name = "cargo", nullable = false, length = 1000)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "infoExperiencia")
	public Set<InfoReferencia> getInfoReferencias() {
		return this.infoReferencias;
	}

	public void setInfoReferencias(Set<InfoReferencia> infoReferencias) {
		this.infoReferencias = infoReferencias;
	}

}
