package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InfoConocimiento generated by hbm2java
 */
@Entity
@Table(name = "info_conocimiento", catalog = "jaioselectiondb")
public class InfoConocimiento implements java.io.Serializable {

	private Integer id;
	private Candidato candidato;
	private String nombre;
	private String nivel;

	public InfoConocimiento() {
	}

	public InfoConocimiento(Candidato candidato, String nombre) {
		this.candidato = candidato;
		this.nombre = nombre;
	}

	public InfoConocimiento(Candidato candidato, String nombre, String nivel) {
		this.candidato = candidato;
		this.nombre = nombre;
		this.nivel = nivel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidato_id", nullable = false)
	public Candidato getCandidato() {
		return this.candidato;
	}

	public void setCandidato(Candidato candidato) {
		this.candidato = candidato;
	}

	@Column(name = "nombre", nullable = false, length = 500)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "nivel", length = 100)
	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

}
