package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InfoAcademica generated by hbm2java
 */
@Entity
@Table(name = "info_academica", catalog = "jaioselectiondb")
public class InfoAcademica implements java.io.Serializable {

	private Integer id;
	private Candidato candidato;
	private Date fechaInicio;
	private Date fechaFin;
	private String nombre;
	private String grado;
	private String logro;
	private String especialidad;

	public InfoAcademica() {
	}

	public InfoAcademica(Candidato candidato, Date fechaInicio, String nombre) {
		this.candidato = candidato;
		this.fechaInicio = fechaInicio;
		this.nombre = nombre;
	}

	public InfoAcademica(Candidato candidato, Date fechaInicio, Date fechaFin, String nombre, String grado,
			String logro, String especialidad) {
		this.candidato = candidato;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.nombre = nombre;
		this.grado = grado;
		this.logro = logro;
		this.especialidad = especialidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidato_id", nullable = false)
	public Candidato getCandidato() {
		return this.candidato;
	}

	public void setCandidato(Candidato candidato) {
		this.candidato = candidato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "grado", length = 200)
	public String getGrado() {
		return this.grado;
	}

	public void setGrado(String grado) {
		this.grado = grado;
	}

	@Column(name = "logro", length = 1000)
	public String getLogro() {
		return this.logro;
	}

	public void setLogro(String logro) {
		this.logro = logro;
	}

	@Column(name = "especialidad", length = 200)
	public String getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

}
