package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModeloEvaluacionXCompetenciaId generated by hbm2java
 */
@Embeddable
public class ModeloEvaluacionXCompetenciaId implements java.io.Serializable {

	private int modeloEvaluacionId;
	private int modeloCompetenciaId;
	private byte esExacto;

	public ModeloEvaluacionXCompetenciaId() {
	}

	public ModeloEvaluacionXCompetenciaId(int modeloEvaluacionId, int modeloCompetenciaId, byte esExacto) {
		this.modeloEvaluacionId = modeloEvaluacionId;
		this.modeloCompetenciaId = modeloCompetenciaId;
		this.esExacto = esExacto;
	}

	@Column(name = "modelo_evaluacion_id", nullable = false)
	public int getModeloEvaluacionId() {
		return this.modeloEvaluacionId;
	}

	public void setModeloEvaluacionId(int modeloEvaluacionId) {
		this.modeloEvaluacionId = modeloEvaluacionId;
	}

	@Column(name = "modelo_competencia_id", nullable = false)
	public int getModeloCompetenciaId() {
		return this.modeloCompetenciaId;
	}

	public void setModeloCompetenciaId(int modeloCompetenciaId) {
		this.modeloCompetenciaId = modeloCompetenciaId;
	}

	@Column(name = "es_exacto", nullable = false)
	public byte getEsExacto() {
		return this.esExacto;
	}

	public void setEsExacto(byte esExacto) {
		this.esExacto = esExacto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModeloEvaluacionXCompetenciaId))
			return false;
		ModeloEvaluacionXCompetenciaId castOther = (ModeloEvaluacionXCompetenciaId) other;

		return (this.getModeloEvaluacionId() == castOther.getModeloEvaluacionId())
				&& (this.getModeloCompetenciaId() == castOther.getModeloCompetenciaId())
				&& (this.getEsExacto() == castOther.getEsExacto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModeloEvaluacionId();
		result = 37 * result + this.getModeloCompetenciaId();
		result = 37 * result + this.getEsExacto();
		return result;
	}

}
