package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModeloCompetenciaSinonimo generated by hbm2java
 */
@Entity
@Table(name = "modelo_competencia_sinonimo", catalog = "jaioselectiondb")
public class ModeloCompetenciaSinonimo implements java.io.Serializable {

	private Integer id;
	private ModeloCompetencia modeloCompetencia;
	private String palabra;

	public ModeloCompetenciaSinonimo() {
	}

	public ModeloCompetenciaSinonimo(ModeloCompetencia modeloCompetencia, String palabra) {
		this.modeloCompetencia = modeloCompetencia;
		this.palabra = palabra;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo_competencia_id", nullable = false)
	public ModeloCompetencia getModeloCompetencia() {
		return this.modeloCompetencia;
	}

	public void setModeloCompetencia(ModeloCompetencia modeloCompetencia) {
		this.modeloCompetencia = modeloCompetencia;
	}

	@Column(name = "palabra", nullable = false, length = 100)
	public String getPalabra() {
		return this.palabra;
	}

	public void setPalabra(String palabra) {
		this.palabra = palabra;
	}

}
