package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModeloPregunta generated by hbm2java
 */
@Entity
@Table(name = "modelo_pregunta", catalog = "jaioselectiondb")
public class ModeloPregunta implements java.io.Serializable {

	private Integer id;
	private ModeloEvaluacion modeloEvaluacion;
	private int tipo;
	private String nombre;
	private int orden;
	private int horasEstimadas;
	private int minutosEstimados;
	private byte[] imagen;
	private int tipoRespuesta;
	private Set<ModeloRespuesta> modeloRespuestas = new HashSet<ModeloRespuesta>(0);

	public ModeloPregunta() {
	}

	public ModeloPregunta(ModeloEvaluacion modeloEvaluacion, int tipo, String nombre, int orden, int horasEstimadas,
			int minutosEstimados, int tipoRespuesta) {
		this.modeloEvaluacion = modeloEvaluacion;
		this.tipo = tipo;
		this.nombre = nombre;
		this.orden = orden;
		this.horasEstimadas = horasEstimadas;
		this.minutosEstimados = minutosEstimados;
		this.tipoRespuesta = tipoRespuesta;
	}

	public ModeloPregunta(ModeloEvaluacion modeloEvaluacion, int tipo, String nombre, int orden, int horasEstimadas,
			int minutosEstimados, byte[] imagen, int tipoRespuesta, Set<ModeloRespuesta> modeloRespuestas) {
		this.modeloEvaluacion = modeloEvaluacion;
		this.tipo = tipo;
		this.nombre = nombre;
		this.orden = orden;
		this.horasEstimadas = horasEstimadas;
		this.minutosEstimados = minutosEstimados;
		this.imagen = imagen;
		this.tipoRespuesta = tipoRespuesta;
		this.modeloRespuestas = modeloRespuestas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo_evaluacion_id", nullable = false)
	public ModeloEvaluacion getModeloEvaluacion() {
		return this.modeloEvaluacion;
	}

	public void setModeloEvaluacion(ModeloEvaluacion modeloEvaluacion) {
		this.modeloEvaluacion = modeloEvaluacion;
	}

	@Column(name = "tipo", nullable = false)
	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	@Column(name = "nombre", nullable = false, length = 300)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@Column(name = "horas_estimadas", nullable = false)
	public int getHorasEstimadas() {
		return this.horasEstimadas;
	}

	public void setHorasEstimadas(int horasEstimadas) {
		this.horasEstimadas = horasEstimadas;
	}

	@Column(name = "minutos_estimados", nullable = false)
	public int getMinutosEstimados() {
		return this.minutosEstimados;
	}

	public void setMinutosEstimados(int minutosEstimados) {
		this.minutosEstimados = minutosEstimados;
	}

	@Column(name = "imagen")
	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	@Column(name = "tipo_respuesta", nullable = false)
	public int getTipoRespuesta() {
		return this.tipoRespuesta;
	}

	public void setTipoRespuesta(int tipoRespuesta) {
		this.tipoRespuesta = tipoRespuesta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloPregunta")
	public Set<ModeloRespuesta> getModeloRespuestas() {
		return this.modeloRespuestas;
	}

	public void setModeloRespuestas(Set<ModeloRespuesta> modeloRespuestas) {
		this.modeloRespuestas = modeloRespuestas;
	}

}
