package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModeloRespuesta generated by hbm2java
 */
@Entity
@Table(name = "modelo_respuesta", catalog = "jaioselectiondb")
public class ModeloRespuesta implements java.io.Serializable {

	private Integer id;
	private ModeloPregunta modeloPregunta;
	private String rptaTexto;
	private byte[] rptaImagen;
	private Integer rptaNumero;
	private Integer numeroOrden;
	private byte esCorrecta;

	public ModeloRespuesta() {
	}

	public ModeloRespuesta(ModeloPregunta modeloPregunta, byte esCorrecta) {
		this.modeloPregunta = modeloPregunta;
		this.esCorrecta = esCorrecta;
	}

	public ModeloRespuesta(ModeloPregunta modeloPregunta, String rptaTexto, byte[] rptaImagen, Integer rptaNumero,
			Integer numeroOrden, byte esCorrecta) {
		this.modeloPregunta = modeloPregunta;
		this.rptaTexto = rptaTexto;
		this.rptaImagen = rptaImagen;
		this.rptaNumero = rptaNumero;
		this.numeroOrden = numeroOrden;
		this.esCorrecta = esCorrecta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo_pregunta_id", nullable = false)
	public ModeloPregunta getModeloPregunta() {
		return this.modeloPregunta;
	}

	public void setModeloPregunta(ModeloPregunta modeloPregunta) {
		this.modeloPregunta = modeloPregunta;
	}

	@Column(name = "rpta_texto", length = 200)
	public String getRptaTexto() {
		return this.rptaTexto;
	}

	public void setRptaTexto(String rptaTexto) {
		this.rptaTexto = rptaTexto;
	}

	@Column(name = "rpta_imagen")
	public byte[] getRptaImagen() {
		return this.rptaImagen;
	}

	public void setRptaImagen(byte[] rptaImagen) {
		this.rptaImagen = rptaImagen;
	}

	@Column(name = "rpta_numero")
	public Integer getRptaNumero() {
		return this.rptaNumero;
	}

	public void setRptaNumero(Integer rptaNumero) {
		this.rptaNumero = rptaNumero;
	}

	@Column(name = "numero_orden")
	public Integer getNumeroOrden() {
		return this.numeroOrden;
	}

	public void setNumeroOrden(Integer numeroOrden) {
		this.numeroOrden = numeroOrden;
	}

	@Column(name = "es_correcta", nullable = false)
	public byte getEsCorrecta() {
		return this.esCorrecta;
	}

	public void setEsCorrecta(byte esCorrecta) {
		this.esCorrecta = esCorrecta;
	}

}
