package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ModeloComunicado generated by hbm2java
 */
@Entity
@Table(name = "modelo_comunicado", catalog = "jaioselectiondb")
public class ModeloComunicado implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String asunto;
	private byte[] contenido;
	private Date fechaRegistro;
	private Date fechaActualizacion;
	private int estado;
	private Set<ComunicadoProceso> comunicadoProcesos = new HashSet<ComunicadoProceso>(0);

	public ModeloComunicado() {
	}

	public ModeloComunicado(String nombre, String asunto, byte[] contenido, Date fechaRegistro, Date fechaActualizacion,
			int estado) {
		this.nombre = nombre;
		this.asunto = asunto;
		this.contenido = contenido;
		this.fechaRegistro = fechaRegistro;
		this.fechaActualizacion = fechaActualizacion;
		this.estado = estado;
	}

	public ModeloComunicado(String nombre, String asunto, byte[] contenido, Date fechaRegistro, Date fechaActualizacion,
			int estado, Set<ComunicadoProceso> comunicadoProcesos) {
		this.nombre = nombre;
		this.asunto = asunto;
		this.contenido = contenido;
		this.fechaRegistro = fechaRegistro;
		this.fechaActualizacion = fechaActualizacion;
		this.estado = estado;
		this.comunicadoProcesos = comunicadoProcesos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "asunto", nullable = false, length = 200)
	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	@Column(name = "contenido", nullable = false)
	public byte[] getContenido() {
		return this.contenido;
	}

	public void setContenido(byte[] contenido) {
		this.contenido = contenido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro", nullable = false, length = 10)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", nullable = false, length = 10)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloComunicado")
	public Set<ComunicadoProceso> getComunicadoProcesos() {
		return this.comunicadoProcesos;
	}

	public void setComunicadoProcesos(Set<ComunicadoProceso> comunicadoProcesos) {
		this.comunicadoProcesos = comunicadoProcesos;
	}

}
