package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModeloLibro generated by hbm2java
 */
@Entity
@Table(name = "modelo_libro", catalog = "jaioselectiondb")
public class ModeloLibro implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String autor;
	private String adaptacion;
	private String resena;
	private Integer horasEstimadas;
	private Integer minutosEstimados;
	private Set<ModeloEvaluacion> modeloEvaluacions = new HashSet<ModeloEvaluacion>(0);

	public ModeloLibro() {
	}

	public ModeloLibro(String nombre) {
		this.nombre = nombre;
	}

	public ModeloLibro(String nombre, String autor, String adaptacion, String resena, Integer horasEstimadas,
			Integer minutosEstimados, Set<ModeloEvaluacion> modeloEvaluacions) {
		this.nombre = nombre;
		this.autor = autor;
		this.adaptacion = adaptacion;
		this.resena = resena;
		this.horasEstimadas = horasEstimadas;
		this.minutosEstimados = minutosEstimados;
		this.modeloEvaluacions = modeloEvaluacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "autor", length = 500)
	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	@Column(name = "adaptacion", length = 500)
	public String getAdaptacion() {
		return this.adaptacion;
	}

	public void setAdaptacion(String adaptacion) {
		this.adaptacion = adaptacion;
	}

	@Column(name = "resena", length = 2000)
	public String getResena() {
		return this.resena;
	}

	public void setResena(String resena) {
		this.resena = resena;
	}

	@Column(name = "horas_estimadas")
	public Integer getHorasEstimadas() {
		return this.horasEstimadas;
	}

	public void setHorasEstimadas(Integer horasEstimadas) {
		this.horasEstimadas = horasEstimadas;
	}

	@Column(name = "minutos_estimados")
	public Integer getMinutosEstimados() {
		return this.minutosEstimados;
	}

	public void setMinutosEstimados(Integer minutosEstimados) {
		this.minutosEstimados = minutosEstimados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloLibro")
	public Set<ModeloEvaluacion> getModeloEvaluacions() {
		return this.modeloEvaluacions;
	}

	public void setModeloEvaluacions(Set<ModeloEvaluacion> modeloEvaluacions) {
		this.modeloEvaluacions = modeloEvaluacions;
	}

}
