package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModeloCompetencia generated by hbm2java
 */
@Entity
@Table(name = "modelo_competencia", catalog = "jaioselectiondb")
public class ModeloCompetencia implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String resena;
	private Set<ModeloCompetenciaSinonimo> modeloCompetenciaSinonimos = new HashSet<ModeloCompetenciaSinonimo>(0);
	private Set<ModeloEvaluacionXCompetencia> modeloEvaluacionXCompetencias = new HashSet<ModeloEvaluacionXCompetencia>(
			0);

	public ModeloCompetencia() {
	}

	public ModeloCompetencia(String nombre) {
		this.nombre = nombre;
	}

	public ModeloCompetencia(String nombre, String resena, Set<ModeloCompetenciaSinonimo> modeloCompetenciaSinonimos,
			Set<ModeloEvaluacionXCompetencia> modeloEvaluacionXCompetencias) {
		this.nombre = nombre;
		this.resena = resena;
		this.modeloCompetenciaSinonimos = modeloCompetenciaSinonimos;
		this.modeloEvaluacionXCompetencias = modeloEvaluacionXCompetencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "resena", length = 2000)
	public String getResena() {
		return this.resena;
	}

	public void setResena(String resena) {
		this.resena = resena;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloCompetencia")
	public Set<ModeloCompetenciaSinonimo> getModeloCompetenciaSinonimos() {
		return this.modeloCompetenciaSinonimos;
	}

	public void setModeloCompetenciaSinonimos(Set<ModeloCompetenciaSinonimo> modeloCompetenciaSinonimos) {
		this.modeloCompetenciaSinonimos = modeloCompetenciaSinonimos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloCompetencia")
	public Set<ModeloEvaluacionXCompetencia> getModeloEvaluacionXCompetencias() {
		return this.modeloEvaluacionXCompetencias;
	}

	public void setModeloEvaluacionXCompetencias(Set<ModeloEvaluacionXCompetencia> modeloEvaluacionXCompetencias) {
		this.modeloEvaluacionXCompetencias = modeloEvaluacionXCompetencias;
	}

}
