package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ModeloEvaluacion generated by hbm2java
 */
@Entity
@Table(name = "modelo_evaluacion", catalog = "jaioselectiondb")
public class ModeloEvaluacion implements java.io.Serializable {

	private Integer id;
	private ModeloLibro modeloLibro;
	private String nombre;
	private int horasEstimadas;
	private int minutosEstimados;
	private BigDecimal validez;
	private BigDecimal confiabilidad;
	private Date fechaCreacion;
	private int estado;
	private byte limiteTiempo;
	private Set<ModeloEvaluacionXCompetencia> modeloEvaluacionXCompetencias = new HashSet<ModeloEvaluacionXCompetencia>(
			0);
	private Set<ModeloPregunta> modeloPreguntas = new HashSet<ModeloPregunta>(0);
	private Set<BateriaEvaluacion> bateriaEvaluacions = new HashSet<BateriaEvaluacion>(0);

	public ModeloEvaluacion() {
	}

	public ModeloEvaluacion(ModeloLibro modeloLibro, String nombre, int horasEstimadas, int minutosEstimados,
			BigDecimal validez, BigDecimal confiabilidad, Date fechaCreacion, int estado, byte limiteTiempo) {
		this.modeloLibro = modeloLibro;
		this.nombre = nombre;
		this.horasEstimadas = horasEstimadas;
		this.minutosEstimados = minutosEstimados;
		this.validez = validez;
		this.confiabilidad = confiabilidad;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.limiteTiempo = limiteTiempo;
	}

	public ModeloEvaluacion(ModeloLibro modeloLibro, String nombre, int horasEstimadas, int minutosEstimados,
			BigDecimal validez, BigDecimal confiabilidad, Date fechaCreacion, int estado, byte limiteTiempo,
			Set<ModeloEvaluacionXCompetencia> modeloEvaluacionXCompetencias, Set<ModeloPregunta> modeloPreguntas,
			Set<BateriaEvaluacion> bateriaEvaluacions) {
		this.modeloLibro = modeloLibro;
		this.nombre = nombre;
		this.horasEstimadas = horasEstimadas;
		this.minutosEstimados = minutosEstimados;
		this.validez = validez;
		this.confiabilidad = confiabilidad;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.limiteTiempo = limiteTiempo;
		this.modeloEvaluacionXCompetencias = modeloEvaluacionXCompetencias;
		this.modeloPreguntas = modeloPreguntas;
		this.bateriaEvaluacions = bateriaEvaluacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo_libro_id", nullable = false)
	public ModeloLibro getModeloLibro() {
		return this.modeloLibro;
	}

	public void setModeloLibro(ModeloLibro modeloLibro) {
		this.modeloLibro = modeloLibro;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "horas_estimadas", nullable = false)
	public int getHorasEstimadas() {
		return this.horasEstimadas;
	}

	public void setHorasEstimadas(int horasEstimadas) {
		this.horasEstimadas = horasEstimadas;
	}

	@Column(name = "minutos_estimados", nullable = false)
	public int getMinutosEstimados() {
		return this.minutosEstimados;
	}

	public void setMinutosEstimados(int minutosEstimados) {
		this.minutosEstimados = minutosEstimados;
	}

	@Column(name = "validez", nullable = false, precision = 5)
	public BigDecimal getValidez() {
		return this.validez;
	}

	public void setValidez(BigDecimal validez) {
		this.validez = validez;
	}

	@Column(name = "confiabilidad", nullable = false, precision = 5)
	public BigDecimal getConfiabilidad() {
		return this.confiabilidad;
	}

	public void setConfiabilidad(BigDecimal confiabilidad) {
		this.confiabilidad = confiabilidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", nullable = false, length = 10)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Column(name = "limite_tiempo", nullable = false)
	public byte getLimiteTiempo() {
		return this.limiteTiempo;
	}

	public void setLimiteTiempo(byte limiteTiempo) {
		this.limiteTiempo = limiteTiempo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloEvaluacion")
	public Set<ModeloEvaluacionXCompetencia> getModeloEvaluacionXCompetencias() {
		return this.modeloEvaluacionXCompetencias;
	}

	public void setModeloEvaluacionXCompetencias(Set<ModeloEvaluacionXCompetencia> modeloEvaluacionXCompetencias) {
		this.modeloEvaluacionXCompetencias = modeloEvaluacionXCompetencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloEvaluacion")
	public Set<ModeloPregunta> getModeloPreguntas() {
		return this.modeloPreguntas;
	}

	public void setModeloPreguntas(Set<ModeloPregunta> modeloPreguntas) {
		this.modeloPreguntas = modeloPreguntas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloEvaluacion")
	public Set<BateriaEvaluacion> getBateriaEvaluacions() {
		return this.bateriaEvaluacions;
	}

	public void setBateriaEvaluacions(Set<BateriaEvaluacion> bateriaEvaluacions) {
		this.bateriaEvaluacions = bateriaEvaluacions;
	}

}
