package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModeloEvaluacionXCompetencia generated by hbm2java
 */
@Entity
@Table(name = "modelo_evaluacion_x_competencia", catalog = "jaioselectiondb")
public class ModeloEvaluacionXCompetencia implements java.io.Serializable {

	private ModeloEvaluacionXCompetenciaId id;
	private ModeloCompetencia modeloCompetencia;
	private ModeloEvaluacion modeloEvaluacion;

	public ModeloEvaluacionXCompetencia() {
	}

	public ModeloEvaluacionXCompetencia(ModeloEvaluacionXCompetenciaId id, ModeloCompetencia modeloCompetencia,
			ModeloEvaluacion modeloEvaluacion) {
		this.id = id;
		this.modeloCompetencia = modeloCompetencia;
		this.modeloEvaluacion = modeloEvaluacion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "modeloEvaluacionId", column = @Column(name = "modelo_evaluacion_id", nullable = false)),
			@AttributeOverride(name = "modeloCompetenciaId", column = @Column(name = "modelo_competencia_id", nullable = false)),
			@AttributeOverride(name = "esExacto", column = @Column(name = "es_exacto", nullable = false)) })
	public ModeloEvaluacionXCompetenciaId getId() {
		return this.id;
	}

	public void setId(ModeloEvaluacionXCompetenciaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo_competencia_id", nullable = false, insertable = false, updatable = false)
	public ModeloCompetencia getModeloCompetencia() {
		return this.modeloCompetencia;
	}

	public void setModeloCompetencia(ModeloCompetencia modeloCompetencia) {
		this.modeloCompetencia = modeloCompetencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelo_evaluacion_id", nullable = false, insertable = false, updatable = false)
	public ModeloEvaluacion getModeloEvaluacion() {
		return this.modeloEvaluacion;
	}

	public void setModeloEvaluacion(ModeloEvaluacion modeloEvaluacion) {
		this.modeloEvaluacion = modeloEvaluacion;
	}

}
