package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notificaciones generated by hbm2java
 */
@Entity
@Table(name = "notificaciones", catalog = "jaioselectiondb")
public class Notificaciones implements java.io.Serializable {

	private Integer id;
	private ProcesoSeleccion procesoSeleccion;
	private String asunto;
	private byte[] contenido;
	private String correo;
	private int estado;
	private Date fechaRegistro;
	private Date fechaEnvio;

	public Notificaciones() {
	}

	public Notificaciones(ProcesoSeleccion procesoSeleccion, String asunto, byte[] contenido, String correo, int estado,
			Date fechaRegistro) {
		this.procesoSeleccion = procesoSeleccion;
		this.asunto = asunto;
		this.contenido = contenido;
		this.correo = correo;
		this.estado = estado;
		this.fechaRegistro = fechaRegistro;
	}

	public Notificaciones(ProcesoSeleccion procesoSeleccion, String asunto, byte[] contenido, String correo, int estado,
			Date fechaRegistro, Date fechaEnvio) {
		this.procesoSeleccion = procesoSeleccion;
		this.asunto = asunto;
		this.contenido = contenido;
		this.correo = correo;
		this.estado = estado;
		this.fechaRegistro = fechaRegistro;
		this.fechaEnvio = fechaEnvio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proceso_seleccion_id", nullable = false)
	public ProcesoSeleccion getProcesoSeleccion() {
		return this.procesoSeleccion;
	}

	public void setProcesoSeleccion(ProcesoSeleccion procesoSeleccion) {
		this.procesoSeleccion = procesoSeleccion;
	}

	@Column(name = "asunto", nullable = false, length = 200)
	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	@Column(name = "contenido", nullable = false)
	public byte[] getContenido() {
		return this.contenido;
	}

	public void setContenido(byte[] contenido) {
		this.contenido = contenido;
	}

	@Column(name = "correo", nullable = false, length = 200)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro", nullable = false, length = 10)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_envio", length = 10)
	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

}
