package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", catalog = "jaioselectiondb")
public class Perfil implements java.io.Serializable {

	private Integer id;
	private Area area;
	private Empresa empresa;
	private String nombre;
	private Date fechaRegistro;
	private int estado;
	private String descripcionFuncion;
	private Set<EvaluacionPerfil> evaluacionPerfils = new HashSet<EvaluacionPerfil>(0);
	private Set<ProcesoSeleccion> procesoSeleccions = new HashSet<ProcesoSeleccion>(0);

	public Perfil() {
	}

	public Perfil(Area area, Empresa empresa, String nombre, Date fechaRegistro, int estado) {
		this.area = area;
		this.empresa = empresa;
		this.nombre = nombre;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
	}

	public Perfil(Area area, Empresa empresa, String nombre, Date fechaRegistro, int estado, String descripcionFuncion,
			Set<EvaluacionPerfil> evaluacionPerfils, Set<ProcesoSeleccion> procesoSeleccions) {
		this.area = area;
		this.empresa = empresa;
		this.nombre = nombre;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
		this.descripcionFuncion = descripcionFuncion;
		this.evaluacionPerfils = evaluacionPerfils;
		this.procesoSeleccions = procesoSeleccions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_id", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empresa_id", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro", nullable = false, length = 10)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Column(name = "descripcion_funcion", length = 2000)
	public String getDescripcionFuncion() {
		return this.descripcionFuncion;
	}

	public void setDescripcionFuncion(String descripcionFuncion) {
		this.descripcionFuncion = descripcionFuncion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<EvaluacionPerfil> getEvaluacionPerfils() {
		return this.evaluacionPerfils;
	}

	public void setEvaluacionPerfils(Set<EvaluacionPerfil> evaluacionPerfils) {
		this.evaluacionPerfils = evaluacionPerfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<ProcesoSeleccion> getProcesoSeleccions() {
		return this.procesoSeleccions;
	}

	public void setProcesoSeleccions(Set<ProcesoSeleccion> procesoSeleccions) {
		this.procesoSeleccions = procesoSeleccions;
	}

}
