package jaio.selection.entity;
// Generated 27/10/2017 01:28:59 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "jaioselectiondb")
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String correo;
	private String nombreCompleto;
	private Date fechaRegistro;
	private int estado;
	private String contrasena;
	private Set<Empresa> empresas = new HashSet<Empresa>(0);

	public Usuario() {
	}

	public Usuario(String correo, String nombreCompleto, Date fechaRegistro, int estado, String contrasena) {
		this.correo = correo;
		this.nombreCompleto = nombreCompleto;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
		this.contrasena = contrasena;
	}

	public Usuario(String correo, String nombreCompleto, Date fechaRegistro, int estado, String contrasena,
			Set<Empresa> empresas) {
		this.correo = correo;
		this.nombreCompleto = nombreCompleto;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
		this.contrasena = contrasena;
		this.empresas = empresas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "correo", nullable = false, length = 200)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "nombre_completo", nullable = false, length = 200)
	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro", nullable = false, length = 10)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Column(name = "contrasena", nullable = false, length = 45)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

}
